package emit

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/Grace/genai-interlingua/internal/dialect"
	"github.com/Grace/genai-interlingua/internal/emit/schemafile"
)

var update = flag.Bool("update", false, "rewrite docs/export-gap.md from the current rules")

const doc = "../../docs/export-gap.md"

// TestExportGapTable generates docs/export-gap.md and fails if the committed
// copy disagrees.
//
// The document exists to be cited. The OTEP drafts in docs/oteps argue that the
// Telemetry Schema File format is missing specific transformation types, and an
// argument like that is worth the count of real mappings that currently need
// them and nothing more. Writing the count by hand into the proposal would make
// it a claim; generating it from the rule tables makes it a measurement, and one
// that goes stale loudly rather than quietly.
func TestExportGapTable(t *testing.T) {
	got, err := table()
	if err != nil {
		t.Fatalf("measure: %v", err)
	}
	if *update {
		if err := os.WriteFile(doc, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(doc)
	if err != nil {
		t.Fatalf("read %s: %v (rerun with -update)", doc, err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s is stale; rerun with -update and read the diff", doc)
	}
}

// TestSchemaFilesCarryLessThanOTTL is the ordering the whole argument depends
// on. If a schema file could express as much as OTTL, there would be nothing to
// propose: the existing format would already be enough and this repository
// would be a lookup table.
func TestSchemaFilesCarryLessThanOTTL(t *testing.T) {
	cov, err := Measure()
	if err != nil {
		t.Fatal(err)
	}
	if len(cov) == 0 {
		t.Fatal("nothing is exportable; this test is checking nothing")
	}
	for _, c := range cov {
		if c.OTTLCarried > c.Processor {
			t.Errorf("%s/%s: OTTL carries %d of %d, which is more than the processor does",
				c.Dialect, c.Target, c.OTTLCarried, c.Processor)
		}
		if c.SchemaFileCarried > c.OTTLCarried {
			t.Errorf("%s/%s: a schema file carries %d and OTTL carries %d."+
				"\n    If this is real rather than an accounting bug, the argument in docs/oteps"+
				"\n    needs rewriting: the existing format would be doing more than claimed.",
				c.Dialect, c.Target, c.SchemaFileCarried, c.OTTLCarried)
		}
	}
}

func table() ([]byte, error) {
	cov, err := Measure()
	if err != nil {
		return nil, err
	}

	total, exportable := 0, 0
	for _, d := range dialect.Dialects() {
		total++
		if _, ok := d.(dialect.Ruled); ok {
			exportable++
		}
	}

	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("# What each export format can carry")
	p("")
	p("<!-- Generated by `go test ./internal/emit -update`. Do not edit. -->")
	p("")
	p("There are three ways a mapping leaves this repository, and they are not")
	p("equivalent. The processor carries everything, because it is Go and Go can read")
	p("a span. [OTTL](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/README.md)")
	p("carries the mappings that are transformations of a *value*. An [OpenTelemetry")
	p("Telemetry Schema File](https://opentelemetry.io/docs/specs/otel/schemas/file_format_v1.1.0/)")
	p("carries only the ones that are changes of a *name*.")
	p("")
	p("This table is measured from the rule tables, not described. It is the evidence")
	p("for [`docs/oteps/`](oteps/): a proposal to add transformation types to a format")
	p("is worth the count of real mappings that currently need them, and this is where")
	p("that count comes from.")
	p("")
	p("## Coverage")
	p("")
	p("| dialect | target | mappings | representable | processor | OTTL | schema file |")
	p("| --- | --- | ---: | ---: | ---: | ---: | ---: |")
	for _, c := range cov {
		p("| `%s` | `%s` | %d | %d | %d | %d | %d |",
			c.Dialect, c.Target, c.Mappings, c.Processor, c.Processor, c.OTTLCarried, c.SchemaFileCarried)
	}
	p("")
	p("**mappings** is every field the dialect can produce. **representable** is how")
	p("many of those the target schema has an attribute for at all — a field the")
	p("target cannot name is not a failure of an export format, so the last three")
	p("columns are measured against it rather than against the first.")
	p("")
	p("The schema file column needs one more split, because most of it is not the")
	p("format succeeding:")
	p("")
	p("| dialect | target | renames written | needed no rename | could not be expressed |")
	p("| --- | --- | ---: | ---: | ---: |")
	for _, c := range cov {
		gaps := 0
		for _, n := range c.Reasons {
			gaps += n
		}
		p("| `%s` | `%s` | %d | %d | %d |",
			c.Dialect, c.Target, c.SchemaFileRenames, c.SchemaFileConformant, gaps)
	}
	p("")
	p("\"Needed no rename\" is the emitter already writing the target's own attribute")
	p("name. It is a property of the emitter, not of the format; counting it as")
	p("coverage would credit the schema file for work nobody did.")
	p("")
	p("## Why the gaps are gaps")
	p("")
	p("Every mapping a schema file could not carry, grouped by the specific")
	p("capability that was missing. The point of naming them this precisely is that")
	p("\"schema files are not expressive enough\" is not a proposal, and \"schema files")
	p("cannot rewrite a value\" is.")
	p("")
	p("| reason | what it means | count |")
	p("| --- | --- | ---: |")
	totals := map[schemafile.Reason]int{}
	for _, c := range cov {
		for r, n := range c.Reasons {
			totals[r] += n
		}
	}
	for _, r := range []schemafile.Reason{
		schemafile.ReasonValueTransform,
		schemafile.ReasonScalarToList,
		schemafile.ReasonAmbiguousPrecedence,
		schemafile.ReasonClosedValueSet,
		schemafile.ReasonNoAttribute,
		schemafile.ReasonNotAName,
	} {
		if totals[r] == 0 {
			continue
		}
		p("| `%s` | %s | %d |", r, reasonProse[r], totals[r])
	}
	p("")
	// Which reasons a format change could fix is a property of the reason, not
	// of how many turned up today, so it is named from the fixable set rather
	// than by counting rows -- a table that happened to render four rows and a
	// sentence that said "the first four" would agree by luck.
	var fixable []string
	fixableTotal := 0
	for _, r := range []schemafile.Reason{
		schemafile.ReasonValueTransform,
		schemafile.ReasonScalarToList,
		schemafile.ReasonAmbiguousPrecedence,
		schemafile.ReasonClosedValueSet,
	} {
		if totals[r] > 0 {
			fixable = append(fixable, "`"+string(r)+"`")
			fixableTotal += totals[r]
		}
	}
	if len(fixable) > 0 {
		p("%s %s what a format change could fix: %d mappings that fail only because",
			join(fixable), plural(len(fixable), "is", "are"), fixableTotal)
		p("the format has no transformation for them. That is the room")
		p("[OTEP 0152](https://github.com/open-telemetry/opentelemetry-specification/blob/main/oteps/0152-telemetry-schemas.md)")
		p("left when it held the transformation set to \"the bare minimum ... with more")
		p("types of transformations potentially proposed in the future\".")
		p("")
	}
	p("`not_a_name` is not one of them. Reassembling `gen_ai.prompt.{i}.tool_calls.{j}.*`")
	p("into one document is a reading of a span, and no declarative schema format")
	p("should try to express it. That one stays in code, and the honest thing to do")
	p("about it is what this repository does: say so on the span.")
	p("")
	p("## The sample")
	p("")
	p("%d of %d dialects declare their mappings as data so far, so that is what can be",
		exportable, total)
	p("measured. The rest are migrating incrementally, and until one is migrated it")
	p("contributes nothing to this table rather than contributing a zero — an")
	p("unmigrated dialect is unmeasured, not unexportable-in-principle, and the")
	p("difference matters to anything that cites these counts.")
	return []byte(b.String()), nil
}

// join renders a list as prose. Strings.Join with " and " reads badly past two
// items, and this list grows every time a dialect is migrated.
func join(in []string) string {
	switch len(in) {
	case 0:
		return ""
	case 1:
		return in[0]
	case 2:
		return in[0] + " and " + in[1]
	}
	return strings.Join(in[:len(in)-1], ", ") + " and " + in[len(in)-1]
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}

var reasonProse = map[schemafile.Reason]string{
	schemafile.ReasonValueTransform:      "the value changes, not the name: provider aliases, operation aliases, case folding, unit conversion",
	schemafile.ReasonScalarToList:        "the target types the attribute as an array and the emitter writes a scalar; a rename cannot change a type",
	schemafile.ReasonAmbiguousPrecedence: "two source spellings for one field where the newer wins; `attribute_map` carries both entries but not the ordering",
	schemafile.ReasonClosedValueSet:      "the target admits a fixed set of values and the emitter can produce others; there is no conditional drop",
	schemafile.ReasonNoAttribute:         "the target schema has no attribute for this field, so there is nothing to rename to",
	schemafile.ReasonNotAName:            "a reading of the span rather than a transformation of an attribute",
}
