// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/semconv/gen. DO NOT EDIT.
//
// Regenerate with `go generate ./internal/semconv/...` after re-vendoring
// upstream with testdata/upstream/refresh.sh. The editorial layer -- which
// concepts are modelled at all -- lives in target.go, not here.

package semconv

// keysV1_41_0 is model/gen-ai/registry.yaml at tag v1.41.0 of
// open-telemetry/semantic-conventions -- the last tagged release whose gen_ai.*
// definitions were live rather than deprecation shims. The fields modelled here
// but missing from this map are the ones the new repository added after the split;
// normalizing to this target drops them, and the normalizer says so.
//
// Source: open-telemetry/semantic-conventions@v1.41.0
// https://raw.githubusercontent.com/open-telemetry/semantic-conventions/v1.41.0/model/gen-ai/registry.yaml
var keysV1_41_0 = map[Field]string{
	ProviderName:               "gen_ai.provider.name",
	RequestModel:               "gen_ai.request.model",
	RequestMaxTokens:           "gen_ai.request.max_tokens",
	RequestChoiceCount:         "gen_ai.request.choice.count",
	RequestTemperature:         "gen_ai.request.temperature",
	RequestTopP:                "gen_ai.request.top_p",
	RequestTopK:                "gen_ai.request.top_k",
	RequestStopSequences:       "gen_ai.request.stop_sequences",
	RequestFrequencyPenalty:    "gen_ai.request.frequency_penalty",
	RequestPresencePenalty:     "gen_ai.request.presence_penalty",
	RequestEncodingFormats:     "gen_ai.request.encoding_formats",
	RequestSeed:                "gen_ai.request.seed",
	RequestStream:              "gen_ai.request.stream",
	ResponseID:                 "gen_ai.response.id",
	ResponseModel:              "gen_ai.response.model",
	ResponseFinishReasons:      "gen_ai.response.finish_reasons",
	ResponseTimeToFirstChunk:   "gen_ai.response.time_to_first_chunk",
	UsageInputTokens:           "gen_ai.usage.input_tokens",
	UsageCacheReadInputTokens:  "gen_ai.usage.cache_read.input_tokens",
	UsageCacheWriteInputTokens: "gen_ai.usage.cache_creation.input_tokens",
	UsageOutputTokens:          "gen_ai.usage.output_tokens",
	UsageReasoningOutputTokens: "gen_ai.usage.reasoning.output_tokens",
	TokenType:                  "gen_ai.token.type",
	ConversationID:             "gen_ai.conversation.id",
	AgentID:                    "gen_ai.agent.id",
	AgentName:                  "gen_ai.agent.name",
	AgentDescription:           "gen_ai.agent.description",
	AgentVersion:               "gen_ai.agent.version",
	ToolName:                   "gen_ai.tool.name",
	ToolCallID:                 "gen_ai.tool.call.id",
	ToolDescription:            "gen_ai.tool.description",
	ToolType:                   "gen_ai.tool.type",
	ToolCallArguments:          "gen_ai.tool.call.arguments",
	ToolCallResult:             "gen_ai.tool.call.result",
	ToolDefinitions:            "gen_ai.tool.definitions",
	DataSourceID:               "gen_ai.data_source.id",
	OperationName:              "gen_ai.operation.name",
	OutputType:                 "gen_ai.output.type",
	EmbeddingsDimensionCount:   "gen_ai.embeddings.dimension.count",
	RetrievalDocuments:         "gen_ai.retrieval.documents",
	RetrievalQueryText:         "gen_ai.retrieval.query.text",
	SystemInstructions:         "gen_ai.system_instructions",
	InputMessages:              "gen_ai.input.messages",
	OutputMessages:             "gen_ai.output.messages",
	EvaluationName:             "gen_ai.evaluation.name",
	EvaluationScoreValue:       "gen_ai.evaluation.score.value",
	EvaluationScoreLabel:       "gen_ai.evaluation.score.label",
	EvaluationExplanation:      "gen_ai.evaluation.explanation",
	PromptName:                 "gen_ai.prompt.name",
	WorkflowName:               "gen_ai.workflow.name",
}

// enumsV1_41_0 is the closed value set for every attribute above that has one.
// A field absent here is open-ended and accepts anything; a value legal
// under another target and absent from a set here is a loss the normalizer
// records, the same as a field with no key at all.
//
// Members come from the registry's own type.members, deduplicated by value:
// upstream can define two members that differ only in id, such as the
// deprecated gen_ai.token.type member spelled completion whose value is output.
var enumsV1_41_0 = map[Field][]string{
	ProviderName: {
		"anthropic",
		"aws.bedrock",
		"azure.ai.inference",
		"azure.ai.openai",
		"cohere",
		"deepseek",
		"gcp.gemini",
		"gcp.gen_ai",
		"gcp.vertex_ai",
		"groq",
		"ibm.watsonx.ai",
		"mistral_ai",
		"openai",
		"perplexity",
		"x_ai",
	},
	TokenType: {
		"input",
		"output",
	},
	OperationName: {
		"chat",
		"create_agent",
		"embeddings",
		"execute_tool",
		"generate_content",
		"invoke_agent",
		"invoke_workflow",
		"retrieval",
		"text_completion",
	},
	OutputType: {
		"image",
		"json",
		"speech",
		"text",
	},
}

// keysGenAIMain is model/gen-ai/registry.yaml on the main branch of
// open-telemetry/semantic-conventions-genai, pinned to the commit named in
// _source.ref of the vendored registry. Every attribute there is stability:
// development; nothing in this schema is stable, including the question of where
// the schema lives.
//
// Source: open-telemetry/semantic-conventions-genai@94f432d7126f
// https://raw.githubusercontent.com/open-telemetry/semantic-conventions-genai/94f432d7126f/model/gen-ai/registry.yaml
var keysGenAIMain = map[Field]string{
	ProviderName:                   "gen_ai.provider.name",
	RequestModel:                   "gen_ai.request.model",
	RequestMaxTokens:               "gen_ai.request.max_tokens",
	RequestChoiceCount:             "gen_ai.request.choice.count",
	RequestTemperature:             "gen_ai.request.temperature",
	RequestTopP:                    "gen_ai.request.top_p",
	RequestTopK:                    "gen_ai.request.top_k",
	RequestStopSequences:           "gen_ai.request.stop_sequences",
	RequestFrequencyPenalty:        "gen_ai.request.frequency_penalty",
	RequestPresencePenalty:         "gen_ai.request.presence_penalty",
	RequestEncodingFormats:         "gen_ai.request.encoding_formats",
	RequestSeed:                    "gen_ai.request.seed",
	RequestStream:                  "gen_ai.request.stream",
	RequestReasoningLevel:          "gen_ai.request.reasoning.level",
	RequestPreviousResponseID:      "gen_ai.request.previous_response.id",
	RequestStreamCursor:            "gen_ai.request.stream_cursor",
	ResponseID:                     "gen_ai.response.id",
	ResponseModel:                  "gen_ai.response.model",
	ResponseFinishReasons:          "gen_ai.response.finish_reasons",
	ResponseStatus:                 "gen_ai.response.status",
	ResponseTimeToFirstChunk:       "gen_ai.response.time_to_first_chunk",
	UsageInputTokens:               "gen_ai.usage.input_tokens",
	UsageCacheReadInputTokens:      "gen_ai.usage.cache_read.input_tokens",
	UsageCacheWriteInputTokens:     "gen_ai.usage.cache_write.input_tokens",
	UsageTextInputTokens:           "gen_ai.usage.text.input_tokens",
	UsageImageInputTokens:          "gen_ai.usage.image.input_tokens",
	UsageAudioInputTokens:          "gen_ai.usage.audio.input_tokens",
	UsageOutputTokens:              "gen_ai.usage.output_tokens",
	UsageReasoningOutputTokens:     "gen_ai.usage.reasoning.output_tokens",
	UsageTextOutputTokens:          "gen_ai.usage.text.output_tokens",
	UsageImageOutputTokens:         "gen_ai.usage.image.output_tokens",
	UsageAudioOutputTokens:         "gen_ai.usage.audio.output_tokens",
	UsageTextCacheReadInputTokens:  "gen_ai.usage.text.cache_read.input_tokens",
	UsageImageCacheReadInputTokens: "gen_ai.usage.image.cache_read.input_tokens",
	UsageAudioCacheReadInputTokens: "gen_ai.usage.audio.cache_read.input_tokens",
	TokenType:                      "gen_ai.token.type",
	ConversationID:                 "gen_ai.conversation.id",
	ConversationCompacted:          "gen_ai.conversation.compacted",
	AgentID:                        "gen_ai.agent.id",
	AgentName:                      "gen_ai.agent.name",
	AgentDescription:               "gen_ai.agent.description",
	AgentVersion:                   "gen_ai.agent.version",
	ToolName:                       "gen_ai.tool.name",
	ToolCallID:                     "gen_ai.tool.call.id",
	ToolDescription:                "gen_ai.tool.description",
	ToolType:                       "gen_ai.tool.type",
	ToolCallArguments:              "gen_ai.tool.call.arguments",
	ToolCallResult:                 "gen_ai.tool.call.result",
	ToolDefinitions:                "gen_ai.tool.definitions",
	DataSourceID:                   "gen_ai.data_source.id",
	OperationName:                  "gen_ai.operation.name",
	OutputType:                     "gen_ai.output.type",
	EmbeddingsDimensionCount:       "gen_ai.embeddings.dimension.count",
	RetrievalDocuments:             "gen_ai.retrieval.documents",
	RetrievalQueryText:             "gen_ai.retrieval.query.text",
	RetrievalTopK:                  "gen_ai.retrieval.top_k",
	MemoryStoreID:                  "gen_ai.memory.store.id",
	MemoryRecordID:                 "gen_ai.memory.record.id",
	MemoryRecordCount:              "gen_ai.memory.record.count",
	MemoryQueryText:                "gen_ai.memory.query.text",
	MemoryRecords:                  "gen_ai.memory.records",
	SystemInstructions:             "gen_ai.system_instructions",
	InputMessages:                  "gen_ai.input.messages",
	OutputMessages:                 "gen_ai.output.messages",
	EvaluationName:                 "gen_ai.evaluation.name",
	EvaluationScoreValue:           "gen_ai.evaluation.score.value",
	EvaluationScoreLabel:           "gen_ai.evaluation.score.label",
	EvaluationExplanation:          "gen_ai.evaluation.explanation",
	PromptName:                     "gen_ai.prompt.name",
	PromptVersion:                  "gen_ai.prompt.version",
	PromptVariable:                 "gen_ai.prompt.variable",
	WorkflowName:                   "gen_ai.workflow.name",
}

// enumsGenAIMain is the closed value set for every attribute above that has one.
// A field absent here is open-ended and accepts anything; a value legal
// under another target and absent from a set here is a loss the normalizer
// records, the same as a field with no key at all.
//
// Members come from the registry's own type.members, deduplicated by value:
// upstream can define two members that differ only in id, such as the
// deprecated gen_ai.token.type member spelled completion whose value is output.
var enumsGenAIMain = map[Field][]string{
	ProviderName: {
		"anthropic",
		"aws.bedrock",
		"azure.ai.inference",
		"azure.ai.openai",
		"cohere",
		"deepseek",
		"gcp.gemini",
		"gcp.gen_ai",
		"gcp.vertex_ai",
		"groq",
		"ibm.watsonx.ai",
		"mistral_ai",
		"moonshot_ai",
		"openai",
		"perplexity",
		"x_ai",
	},
	ResponseStatus: {
		"cancelled",
		"completed",
		"failed",
		"in_progress",
		"incomplete",
		"queued",
	},
	TokenType: {
		"input",
		"output",
	},
	OperationName: {
		"chat",
		"create_agent",
		"create_memory",
		"create_memory_store",
		"delete_memory",
		"delete_memory_store",
		"embeddings",
		"execute_tool",
		"fetch_response",
		"generate_content",
		"invoke_agent",
		"invoke_workflow",
		"plan",
		"retrieval",
		"search_memory",
		"text_completion",
		"update_memory",
		"upsert_memory",
	},
	OutputType: {
		"image",
		"json",
		"speech",
		"text",
	},
}
