#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

"""Writes the demo's sample payloads from testdata/*/in.json.

The pages run against the same spans the test suite runs against. That is the
only arrangement worth having: a demo whose inputs are maintained separately
from the fixtures shows spans nothing has been tested on, and drifts silently
the first time a capture is re-run.

Each fixture's PROVENANCE marker travels with it, so the page can say whether a
span was captured from a real library or written by hand, rather than letting a
reader assume the flattering answer.

    ./demos/samples.py <output.js>
"""

import json
import pathlib
import sys

LABELS = {
    "openllmetry": "OpenLLMetry (current)",
    "openllmetry-legacy": "OpenLLMetry (pre-conventions)",
    "openinference": "OpenInference / Arize",
    "litellm": "LiteLLM",
    "braintrust": "Braintrust",
    "vercel": "Vercel AI SDK",
    "langchain": "LangChain",
    "raw": "Conventions-native",
    "raw-folk": "Folk spellings",
}


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    root = pathlib.Path(__file__).resolve().parent.parent
    out = {}

    for d in sorted((root / "testdata").iterdir()):
        payload = d / "in.json"
        if not payload.is_file():
            continue
        marker = d / "PROVENANCE"
        out[d.name] = {
            # A fixture with no label is listed under its directory name rather
            # than skipped: a new one should appear on the page the day it is
            # added, looking unfinished, instead of being silently absent.
            "label": LABELS.get(d.name, d.name),
            "origin": marker.read_text().strip() if marker.is_file() else "unrecorded",
            "payload": json.loads(payload.read_text()),
        }

    if not out:
        print("no fixtures found under testdata/", file=sys.stderr)
        return 1

    body = json.dumps(out, indent=2, sort_keys=True)
    pathlib.Path(sys.argv[1]).write_text(
        "// Generated by demos/samples.py from testdata/*/in.json in "
        "Grace/genai-interlingua.\n"
        "// Do not edit: these are the fixtures the test suite runs against.\n"
        f"const SAMPLES = {body};\n"
    )
    print(f"wrote {sys.argv[1]}: {len(out)} captures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
