package normalize

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/Grace/genai-interlingua/internal/dialect"
	"github.com/Grace/genai-interlingua/internal/semconv"
)

const conformanceDoc = "../../docs/conformance.md"

// coverage is what one dialect's fixtures demonstrated, accumulated across
// every span in them. A dialect whose fixture is a single trace of three spans
// is credited with the union: the AI SDK splits one model call across an outer
// span, an adapter span and a tool span, and no one of them alone shows what
// the dialect does.
type coverage struct {
	name        dialect.Name
	provenance  map[string]bool
	fields      map[semconv.Field]bool
	dialectLoss map[dialect.Reason]map[string]bool
	targetLoss  map[semconv.Target]map[Reason]map[string]bool
}

func newCoverage(name dialect.Name) *coverage {
	c := &coverage{
		name:        name,
		provenance:  make(map[string]bool),
		fields:      make(map[semconv.Field]bool),
		dialectLoss: make(map[dialect.Reason]map[string]bool),
		targetLoss:  make(map[semconv.Target]map[Reason]map[string]bool),
	}
	for _, t := range semconv.Targets {
		c.targetLoss[t] = make(map[Reason]map[string]bool)
	}
	return c
}

func (c *coverage) observe(r Result, target semconv.Target) {
	// Fields are recovered from the rendered keys rather than tracked
	// separately, so this table can only credit a field the pipeline actually
	// emitted end to end. A field the dialect parsed and the target dropped
	// shows up as a target loss below, which is the honest place for it.
	for key := range r.Set {
		if strings.HasPrefix(key, "interlingua.") {
			continue
		}
		if f, ok := semconv.FieldForKey(key); ok {
			c.fields[f] = true
		}
	}
	for _, l := range r.DialectLoss {
		if c.dialectLoss[l.Reason] == nil {
			c.dialectLoss[l.Reason] = make(map[string]bool)
		}
		c.dialectLoss[l.Reason][l.Key] = true
	}
	for _, l := range r.TargetLoss {
		if c.targetLoss[target][l.Reason] == nil {
			c.targetLoss[target][l.Reason] = make(map[string]bool)
		}
		c.targetLoss[target][l.Reason][l.Key] = true
	}
}

// TestConformanceTable regenerates docs/conformance.md from the fixtures and
// fails when the committed file has drifted from it. The table is the
// repository's claim about what it supports, and a claim maintained by hand
// stops being true the first time somebody forgets. This one cannot be edited
// into agreement with a mapping that does not exist: it is derived from running
// the mapping.
func TestConformanceTable(t *testing.T) {
	inputs, err := filepath.Glob(filepath.Join(testdata, "*", "in.json"))
	if err != nil {
		t.Fatalf("glob fixtures: %v", err)
	}
	if len(inputs) == 0 {
		t.Fatalf("no fixtures under %s", testdata)
	}
	sort.Strings(inputs)

	byDialect := make(map[dialect.Name]*coverage)
	var order []dialect.Name

	for _, input := range inputs {
		payload := mustReadFile(t, input)
		// Provenance is read from a marker beside the fixture rather than
		// asserted in the prose below, so that the table's account of where its
		// inputs came from cannot drift from where they actually came from.
		provenance := strings.TrimSpace(string(mustReadFile(t, filepath.Join(filepath.Dir(input), "PROVENANCE"))))
		for _, target := range semconv.Targets {
			opts := DefaultOptions()
			opts.Target = target

			for _, s := range spansOf(t, payload) {
				r, ok := Span(s, opts)
				if !ok {
					continue
				}
				c := byDialect[r.Dialect]
				if c == nil {
					c = newCoverage(r.Dialect)
					byDialect[r.Dialect] = c
					order = append(order, r.Dialect)
				}
				c.provenance[provenance] = true
				c.observe(r, target)
			}
		}
	}
	sort.Slice(order, func(i, j int) bool { return order[i] < order[j] })

	got := renderConformance(order, byDialect)
	if *update {
		if err := os.WriteFile(conformanceDoc, []byte(got), 0o644); err != nil {
			t.Fatalf("write %s: %v", conformanceDoc, err)
		}
		return
	}
	if want := string(mustReadFile(t, conformanceDoc)); got != want {
		t.Errorf("%s has drifted from what the fixtures produce\n%s\nrerun with -update to regenerate",
			conformanceDoc, firstDifference([]byte(want), []byte(got)))
	}
}

// spansOf decodes a fixture into the spans the dialects see. It goes through
// the same codec the CLI uses rather than a second reader, so the table cannot
// describe a pipeline different from the one that runs.
func spansOf(t *testing.T, data []byte) []dialect.Span {
	t.Helper()
	var p payload
	if err := json.Unmarshal(data, &p); err != nil {
		t.Fatalf("decode fixture: %v", err)
	}
	var out []dialect.Span
	for _, rs := range p.ResourceSpans {
		for _, ss := range rs.ScopeSpans {
			for _, s := range ss.Spans {
				out = append(out, s.parsed())
			}
		}
	}
	return out
}

func renderConformance(order []dialect.Name, byDialect map[dialect.Name]*coverage) string {
	var b strings.Builder

	b.WriteString(`# Conformance

Generated by ` + "`TestConformanceTable`" + ` in ` + "`internal/normalize`" + `. Do not edit by hand:
` + "`go test ./internal/normalize -update`" + ` rewrites it, and CI fails when this file
and the fixtures disagree.

## What this table is, and is not

It reports what the fixtures **demonstrated**, not what a dialect is capable of.
A field with no mark against a dialect means that dialect's fixtures never
carried one, which is usually because the emitter has nothing to put there and
occasionally because the fixture does not exercise it. Read a mark as evidence
and a blank as silence.

Where the inputs came from matters for how much this table is worth. A row
built from a **captured** fixture is a claim about what that library really
emits, recorded by running it. A row built from a **hand-built** fixture is a
claim this repository makes about the library, checked only against itself.
Both are listed below, per dialect, and ` + "`testdata/capture/capture.sh`" + `
regenerates the captured ones.

`)

	fmt.Fprintf(&b, "## Fixture provenance\n\n")
	writeRow(&b, []string{"Dialect", "Inputs"})
	writeRow(&b, []string{"---", "---"})
	for _, n := range order {
		writeRow(&b, []string{"`" + string(n) + "`", strings.Join(sortedKeys(byDialect[n].provenance), ", ")})
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "## Field coverage\n\n")
	b.WriteString("`y` means the normalized span carried the field. The two target\n")
	b.WriteString("columns say whether that schema version can express it at all: a field\n")
	b.WriteString("marked `-` under a target is dropped when normalizing to it, however well\n")
	b.WriteString("the dialect parsed it.\n\n")

	header := []string{"Field", string(semconv.TargetV1_41_0), string(semconv.TargetGenAIMain)}
	for _, n := range order {
		header = append(header, string(n))
	}
	writeRow(&b, header)
	sep := make([]string, len(header))
	for i := range sep {
		sep[i] = "---"
	}
	writeRow(&b, sep)

	for _, f := range semconv.AllFields {
		carried := false
		for _, n := range order {
			if byDialect[n].fields[f] {
				carried = true
				break
			}
		}
		if !carried {
			continue
		}
		row := []string{"`" + semconv.CanonicalKey(f) + "`",
			mark(semconv.TargetV1_41_0.Represents(f)), mark(semconv.TargetGenAIMain.Represents(f))}
		for _, n := range order {
			row = append(row, mark(byDialect[n].fields[f]))
		}
		writeRow(&b, row)
	}

	// A field whose key differs between targets is the entire subject of this
	// repository, and naming rows by the canonical key would hide it. The note
	// is generated from the key maps rather than written down, so a second
	// rename upstream turns up here without anyone remembering to add it.
	var renamed []string
	for _, f := range semconv.AllFields {
		frozen, okFrozen := semconv.TargetV1_41_0.Key(f)
		main, okMain := semconv.TargetGenAIMain.Key(f)
		if okFrozen && okMain && frozen != main {
			renamed = append(renamed, fmt.Sprintf("`%s` is spelled `%s` at %s",
				main, frozen, semconv.TargetV1_41_0))
		}
	}
	if len(renamed) > 0 {
		fmt.Fprintf(&b, "\nRows are named by the key the field takes at %s. One field is\n"+
			"spelled differently at the two targets: %s.\n",
			semconv.TargetGenAIMain, strings.Join(renamed, "; "))
	}

	b.WriteString("\n## What each dialect could not carry\n\n")
	b.WriteString("Source attributes the emitter wrote that no field could hold, by reason.\n")
	b.WriteString("This is the list `COMPATIBILITY.md` explains and `interlingua.lossy`\n")
	b.WriteString("reports on the span itself.\n")

	for _, n := range order {
		c := byDialect[n]
		fmt.Fprintf(&b, "\n### %s\n\n", n)
		if len(c.dialectLoss) == 0 {
			b.WriteString("Nothing. Every attribute the fixtures carried had somewhere to go.\n")
			continue
		}
		for _, reason := range dialectReasons {
			keys := sortedKeys(c.dialectLoss[reason])
			if len(keys) == 0 {
				continue
			}
			fmt.Fprintf(&b, "- **%s** — %s\n", reason, code(keys))
		}
	}

	b.WriteString("\n## What each target could not express\n\n")
	b.WriteString("Fields the dialects parsed successfully that the schema version has no\n")
	b.WriteString("attribute, or no value, for. This is the cost of pinning, and the reason\n")
	b.WriteString("the default target is a decision rather than a constant.\n")

	for _, target := range semconv.Targets {
		fmt.Fprintf(&b, "\n### %s\n\n", target)
		empty := true
		for _, n := range order {
			c := byDialect[n]
			var lines []string
			for _, reason := range targetReasons {
				keys := sortedKeys(c.targetLoss[target][reason])
				if len(keys) == 0 {
					continue
				}
				lines = append(lines, fmt.Sprintf("  - **%s** — %s", reason, code(keys)))
			}
			if len(lines) == 0 {
				continue
			}
			empty = false
			fmt.Fprintf(&b, "- %s\n%s\n", n, strings.Join(lines, "\n"))
		}
		if empty {
			b.WriteString("Nothing. Every field the dialects produced is expressible here.\n")
		}
	}

	return b.String()
}

// dialectReasons and targetReasons fix the order the reason codes appear in, so
// the generated file is stable and a diff of it is a diff in the mapping.
var dialectReasons = []dialect.Reason{
	dialect.ReasonNoField,
	dialect.ReasonUnstructured,
	dialect.ReasonFlattened,
	dialect.ReasonCoerced,
	dialect.ReasonAmbiguous,
}

var targetReasons = []Reason{ReasonNoAttribute, ReasonNoValue}

func mark(ok bool) string {
	if ok {
		return "y"
	}
	return "-"
}

func code(keys []string) string {
	quoted := make([]string, 0, len(keys))
	for _, k := range keys {
		quoted = append(quoted, "`"+k+"`")
	}
	return strings.Join(quoted, ", ")
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func writeRow(b *strings.Builder, cells []string) {
	b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
}
