package normalize

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// TestFixtureKeys records the set of attribute keys each captured fixture
// carries, and fails when it changes.
//
// This is the drift detector for the *emitters*, and it works on key sets
// rather than bytes for a specific reason: re-capturing produces new trace ids
// and new timestamps every time, so a byte comparison is dirty on every run and
// therefore useless as a signal. What actually matters is whether a library
// started emitting an attribute, or stopped.
//
// That is exactly what OpenLLMetry's migration to the conventions looked like,
// and it was caught by someone happening to read a capture rather than by
// anything here noticing. Re-run testdata/capture/capture.sh, regenerate with
// -update, and a changed KEYS file is the library having changed under you.
func TestFixtureKeys(t *testing.T) {
	inputs, err := filepath.Glob(filepath.Join(testdata, "*", "in.json"))
	if err != nil {
		t.Fatalf("glob fixtures: %v", err)
	}
	if len(inputs) == 0 {
		t.Fatalf("no fixtures under %s", testdata)
	}

	for _, input := range inputs {
		dir := filepath.Dir(input)
		name := filepath.Base(dir)
		t.Run(name, func(t *testing.T) {
			got := renderKeys(t, mustReadFile(t, input))
			path := filepath.Join(dir, "KEYS")

			if *update {
				if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
					t.Fatalf("write %s: %v", path, err)
				}
				return
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read %s: %v (rerun with -update)", path, err)
			}
			if got != string(want) {
				t.Errorf("%s has drifted.\n%s\nIf a capture was just re-run, this is the "+
					"library changing what it emits, and is worth reading before regenerating.",
					path, firstDifference(want, []byte(got)))
			}
		})
	}
}

// renderKeys lists every attribute key on every span in the payload, sorted and
// deduplicated, with the span names above them. Span names are included because
// a library renaming its spans is the same class of change as renaming its
// attributes, and just as invisible in a byte diff full of fresh trace ids.
func renderKeys(t *testing.T, data []byte) string {
	t.Helper()
	var p payload
	if err := json.Unmarshal(data, &p); err != nil {
		t.Fatalf("decode fixture: %v", err)
	}

	names := map[string]bool{}
	attrs := map[string]bool{}
	for _, rs := range p.ResourceSpans {
		for _, ss := range rs.ScopeSpans {
			for _, s := range ss.Spans {
				names[s.Name] = true
				for _, kv := range s.Attributes {
					attrs[kv.Key] = true
				}
			}
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by TestFixtureKeys. Regenerate:\n")
	b.WriteString("#   go test ./internal/normalize -update\n")
	b.WriteString("#\n")
	b.WriteString("# A change here is the emitter changing what it produces.\n\n")
	b.WriteString("[spans]\n")
	for _, n := range sortedSet(names) {
		b.WriteString(n + "\n")
	}
	b.WriteString("\n[attributes]\n")
	for _, k := range sortedSet(attrs) {
		b.WriteString(k + "\n")
	}
	return b.String()
}

func sortedSet(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
